### PR TITLE
FUSETOOLS-2263 - adapt to Fuse Tooling API change

### PR DESCRIPTION
**Pull request by apupier**
to be checked and launched when https://github.com/jbosstools/jbosstools-fuse/pull/945 has been merged

### CODE REVIEW

**Comment by apupier** [comment]
i wasn't able to have test running fine locally in my development environment.

The CI failure will occur until the above mentioned PR is merged and code published on the update site

**Comment by apupier** [comment]
testPR

**Comment by lhein** [comment]
testPR

**Review by lhein — APPROVED** [review]
Ok if build is green

**Pull request merged**
