### PR TITLE
Fusetools 3076 have s ap tooling java11 compatible

### PR DESCRIPTION
**Pull request by apupier**
to be merged before https://github.com/jbosstools/jbosstools-fuse-extras/pull/97

# Pull Request Checklist

## General

- [ ] Did you use the Jira Issue number in the commit comments?
- [ ] Did you set meaningful commit comments on each commit?
- [ ] Did you sign off all commits for this PR? (git commit -s -m "jira issue number - your commit comment")

## Function

- [ ] Does the project still build fine locally?
- [ ] Does your modification work?
- [ ] Is the non-happy path working, too?
- [ ] Are other parts that use the same component still working fine?

## Code Style

- [ ] Are method-/class-/variable-names meaningful?
- [ ] Are methods concise, not too long?
- [ ] Are catch blocks catching precise Exceptions only (no catch all)?
- [ ] Have you used the correct file header copyright comment?
- [ ] Have you set the correct year in the headers of new files?

## Tests

- [ ] Are there unit-tests?
- [ ] Are there integration tests (or at least a jira to tackle these)?

### CODE REVIEW

**Comment by apupier** [comment]
co,nfigured job with jdk 11 to test this PR: https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/Devstudio/view/jdkNext/job/jbosstools-fuse-extras-jdk11_master/34/testReport/org.fusesource.ide.sap.ui.tests.integration/SapGlobalConfigurationWizardIT/testGeneratesCorrectGlobalNodeForBlueprint/

I think the error is because the fuse features which includes common.jaxb has not been merged yet

**Comment by apupier** [comment]
java 11 build is green https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/Devstudio/view/jdkNext/job/jbosstools-fuse-extras-jdk11_master/38/

**Comment by apupier** [comment]
@lhein @bfitzpat Can you review this PR please?

**Review by bfitzpat — APPROVED** [review]
+1 since we have a green build there now too

**Pull request merged**
