### PR TITLE
FUSETOOLS-2936 - upgrade to Eclipse Photon TP

### PR DESCRIPTION
**Pull request by lhein**
Signed-off-by: Lars Heinemann <lhein.smx@gmail.com>

# Pull Request Checklist

## General

- [x] Did you use the Jira Issue number in the commit comments?
- [x] Did you set meaningful commit comments on each commit?
- [x] Did you sign off all commits for this PR? (git commit -s -m "jira issue number - your commit comment")

## Function

- [ ] Does the project still build fine locally?
- [ ] Does your modification work?
- [ ] Is the non-happy path working, too?
- [ ] Are other parts that use the same component still working fine?

## Code Style

- [ ] Are method-/class-/variable-names meaningful?
- [ ] Are methods concise, not too long?
- [ ] Are catch blocks catching precise Exceptions only (no catch all)?
- [ ] Have you used the correct file header copyright comment?
- [ ] Have you set the correct year in the headers of new files?

## Tests

- [x] Are there unit-tests?
- [x] Are there integration tests (or at least a jira to tackle these)?

### CODE REVIEW

**Comment by lhein** [comment]
will not build because JBT does not have a filled update site for photon yet

**Review by bfitzpat — DISMISSED** [review]
+1 - tests fail locally, but it builds ok - once the tests run ok on Jenkins I think we're ok

**Comment by bfitzpat** [comment]
Building again locally with tests with the new change

**Review by bfitzpat — APPROVED** [review]
Builds fine up on Jenkins - I think we're good

**Comment by lhein** [comment]
build is green so I merged

**Pull request merged**
