### PR TITLE
FUSETOOLS-2931 - bump version to 11.0.0

### PR DESCRIPTION
**Pull request by lhein**
Signed-off-by: Lars Heinemann <lhein.smx@gmail.com>

# Pull Request Checklist

## General

- [ ] Did you use the Jira Issue number in the commit comments?
- [ ] Did you set meaningful commit comments on each commit?
- [ ] Did you sign off all commits for this PR? (git commit -s -m "jira issue number - your commit comment")

## Function

- [ ] Does the project still build fine locally?
- [ ] Does your modification work?
- [ ] Is the non-happy path working, too?
- [ ] Are other parts that use the same component still working fine?

## Code Style

- [ ] Are method-/class-/variable-names meaningful?
- [ ] Are methods concise, not too long?
- [ ] Are catch blocks catching precise Exceptions only (no catch all)?
- [ ] Have you used the correct file header copyright comment?
- [ ] Have you set the correct year in the headers of new files?

## Tests

- [ ] Are there unit-tests?
- [ ] Are there integration tests (or at least a jira to tackle these)?

### CODE REVIEW

**Comment by lhein** [comment]
This PR will result in fuse extras being uploaded to the oxygen snapshots site when merged. We will need to update the publish site to photon.

**Comment by lhein** [comment]
no problem as we are still using oxygen tp and its just the snapshots update site

**Comment by lhein** [comment]
Waiting for 11.0 bump build gets uploaded to the update site to have this PR build fine

**Comment by lhein** [comment]
testPR

**Comment by lhein** [comment]
testPR

**Comment by lhein** [comment]
testPR

**Review by apupier — APPROVED** [review]

**Comment by lhein** [comment]
overriding QE approval

**Pull request merged**
