### PR TITLE
JBIDE-27320 Remove JRE7 variable from POM

### PR DESCRIPTION
**Pull request by jkopriva**
Signed-off-by: Josef Kopriva <jkopriva@redhat.com>

# Pull Request Checklist

## General

- [ ] Did you use the Jira Issue number in the commit comments?
- [ ] Did you set meaningful commit comments on each commit?
- [ ] Did you sign off all commits for this PR? (git commit -s -m "jira issue number - your commit comment")

## Function

- [ ] Does the project still build fine locally?
- [ ] Does your modification work?
- [ ] Is the non-happy path working, too?
- [ ] Are other parts that use the same component still working fine?

## Code Style

- [ ] Are method-/class-/variable-names meaningful?
- [ ] Are methods concise, not too long?
- [ ] Are catch blocks catching precise Exceptions only (no catch all)?
- [ ] Have you used the correct file header copyright comment?
- [ ] Have you set the correct year in the headers of new files?

## Tests

- [ ] Are there unit-tests?
- [ ] Are there integration tests (or at least a jira to tackle these)?

### CODE REVIEW

**Review by apupier — APPROVED** [review]

**Review by djelinek — APPROVED** [review]

**Comment by djelinek** [comment]
testPR

**Comment by apupier** [comment]
I think it is failing because "org.jboss.tools:parent:pom:4.16.0.Final-SNAPSHOT " artifact is no more available.

looking

**Comment by apupier** [comment]
or maybe "http://fuse-qe.hosts.prod.upshift.rdu2.redhat.com:8081/" is unreachable. I cannot access it locally (vpn connected) 
Why is it using this repo?

**Comment by djelinek** [comment]
my guess is the unreachable DNS server so I changed it to url which automatically redirects to right place (http://nexus.fuse-qe.eng.rdu2.redhat.com/repository/jbdsis-qe/).. so we will need to rebuild PR check job to verify new settings

**Comment by jkopriva** [comment]
@apupier @djelinek thank you, merging!

**Pull request merged**
