### PR TITLE
update the uri for the new sap p2 repo

### PR DESCRIPTION
**Pull request by lhein**
Signed-off-by: Lars Heinemann <lhein.smx@gmail.com>

# Pull Request Checklist

## General

- [ ] Did you use the Jira Issue number in the commit comments?
- [ ] Did you set meaningful commit comments on each commit?
- [ ] Did you sign off all commits for this PR? (git commit -s -m "jira issue number - your commit comment")

## Function

- [ ] Does the project still build fine locally?
- [ ] Does your modification work?
- [ ] Is the non-happy path working, too?
- [ ] Are other parts that use the same component still working fine?

## Code Style

- [ ] Are method-/class-/variable-names meaningful?
- [ ] Are methods concise, not too long?
- [ ] Are catch blocks catching precise Exceptions only (no catch all)?
- [ ] Have you used the correct file header copyright comment?
- [ ] Have you set the correct year in the headers of new files?

## Tests

- [ ] Are there unit-tests?
- [ ] Are there integration tests (or at least a jira to tackle these)?

### CODE REVIEW

**Comment by apupier** [comment]
this PR seems fine.
I think we need to await that we are sure it is now fine in fuse-components:
- When the update site is rebuilt?
- When rebuilt, is it overriding or adding a new version alongside?
- need to check that a new push is done to check that the update site is still valid
- is the current fuse-components ready: is productization compliant? which job is building it? launching test? pushing artefacts?

**Comment by lhein** [comment]
When checking the update site it looks fine. We have folders for main versions and then subfolders for specific builds in each folder. So from that point of view all should be good. The update sites are only built whenever changes occur. For 6.3 we have the jobs in the Fuse Jenkins named fuse-components-camel-sap-6-3-x-.....
For Fuse 7 the name of the job which I used for testing the build is fuse-components-camel-sap-7-4-x-checkin. For productization builds we still have to check with Jon/Zoran if the SAP P2 generation is called from the pipeline or not but which is not really relevant for this PR.

**Comment by apupier** [comment]
it looks alike the push to the update site has worked a single time (I notice a single version in the http://tooling.fuse-qe.eng.rdu2.redhat.com/p2/fuse.sap.updatesite/7.4.0/latest/all/repo/features/ folder) so I would say that it is still relevant to know if it is workign or not.
And there is a single build in success on https://fusesource-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/fuse-components-camel-sap-7-4-x-checkin/ which seems to say that there is something wrong in the process. (reported https://issues.jboss.org/browse/ENTESB-10930 for this failure)

**Comment by apupier** [comment]
the SAP Fuse components build has been fixed.
The new version pushed is a 7.5 (before it was 7.4) so it is still not testing several push in the same folder.

**Comment by apupier** [comment]
seems there is another problem with the fuse components job (at least with the naming of it), reported https://issues.jboss.org/browse/FUSETOOLS-3265

**Comment by apupier** [comment]
> seems there is another problem with the fuse components job (at least with the naming of it), reported https://issues.jboss.org/browse/FUSETOOLS-3265

reported issue fixed.

but currently upstream job is failing https://fusesource-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/fuse-components-camel-sap-7-x-checkin/

`[ERROR] Failed to execute goal org.eclipse.tycho:tycho-packaging-plugin:1.3.0:validate-version (default-validate-version) on project org.fusesource.camel.component.sap.feature: Unqualified OSGi version 7.5.0.qualifier must match unqualified Maven version 7.6.0-SNAPSHOT for SNAPSHOT builds -> [Help 1]`

**Comment by apupier** [comment]
upstream job has been fixed.
I launched the job 2 times, so pushing two times consecutively is working.
if we upgrade to 7.6.0, seems good to go now

**Review by apupier — APPROVED** [review]

**Pull request merged**
