### PR TITLE
FUSETOOLS-2698: Execute Fuse SAP UI smoke tests after each PR

### PR DESCRIPTION
**Pull request by apodhrad**
Signed-off-by: Andrej Podhradsky <apodhrad@redhat.com>

### CODE REVIEW

**Comment by apodhrad** [comment]
testPR

**Comment by apodhrad** [comment]
testPR

**Comment by apodhrad** [comment]
At the moment, there is only one UI tests executed (the fastest one). The appropriated verification job has been successfully configured.

**Comment by apodhrad** [comment]
testPR

**Comment by apodhrad** [comment]
testPR

**Review by lhein — DISMISSED** [review]

**Comment by apodhrad** [comment]
I rebased the PR and updated the readme file. The verification job passed.

**Review by tsedmik — APPROVED** [review]

**Pull request merged**
